require: rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 80

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 100

Style/Documentation:
  Enabled: false

RSpec/ExampleLength:
  Max: 10